server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb # Власна БД
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console